
package visual;
import javax.swing.table.DefaultTableModel;
import controlador.PeliculaBD;
import java.sql.SQLException;


public class VntInicio extends javax.swing.JFrame {

    PeliculaBD PeliculaBD = new PeliculaBD();
    VtnRegistro objRegistro = null;
    
    public VntInicio() {

        initComponents();
        DefaultTableModel modelo = new DefaultTableModel();
        this.tablePeliculas.setModel(modelo);

        PeliculaBD.abrir();
        
         try {   
            while(PeliculaBD.informacionTabla().next()){
                Object [] fila = new Object [6];
                
                for(int x=0; x<6; x++){
                    fila [x] = PeliculaBD.informacionTabla().getObject(x+1);
                }
                modelo.addRow(fila);
            }
        } catch (SQLException ex) {
            System.out.println("Error en agregar fila a tabla Pelicula");
            System.out.println(ex.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablePeliculas = new javax.swing.JTable();
        lbPeliRegistradas = new javax.swing.JLabel();
        lbFunRegistradas = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableFunciones = new javax.swing.JTable();
        btnCerrarSesion = new javax.swing.JButton();
        MenuGeneral = new javax.swing.JMenuBar();
        mnRegistroEmpleado = new javax.swing.JMenu();
        mnRegistroPeliculas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Inicio");

        tablePeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Duracion", "Clasificacion", "Genero", "Idioma"
            }
        ));
        jScrollPane1.setViewportView(tablePeliculas);

        lbPeliRegistradas.setText("Peliculas Registradas");

        lbFunRegistradas.setText("Funciones Resgitradas");

        tableFunciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo Pelicula", "Hora", "Capacidad", "Numero de Sala", "Tipo de Sala"
            }
        ));
        jScrollPane3.setViewportView(tableFunciones);

        btnCerrarSesion.setText("Cerrar Sesion");

        mnRegistroEmpleado.setText("Registro Empleados");
        mnRegistroEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRegistroEmpleadoActionPerformed(evt);
            }
        });
        MenuGeneral.add(mnRegistroEmpleado);

        mnRegistroPeliculas.setText("Registros Peliculas");
        mnRegistroPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRegistroPeliculasActionPerformed(evt);
            }
        });
        MenuGeneral.add(mnRegistroPeliculas);

        setJMenuBar(MenuGeneral);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPeliRegistradas)
                            .addComponent(lbFunRegistradas)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCerrarSesion)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbPeliRegistradas)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(lbFunRegistradas)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnRegistroPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRegistroPeliculasActionPerformed
        /*if (objRegistro == null)
            objRegistro = new VtnRegistro(this, objRegistro);
        
        objVntAl.setVisible(true);
        
        //Ocultar la ventana Principal
        this.setVisible(false);*/
    }//GEN-LAST:event_mnRegistroPeliculasActionPerformed

    private void mnRegistroEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRegistroEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnRegistroEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VntInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VntInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VntInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VntInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VntInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuGeneral;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbFunRegistradas;
    private javax.swing.JLabel lbPeliRegistradas;
    private javax.swing.JMenu mnRegistroEmpleado;
    private javax.swing.JMenu mnRegistroPeliculas;
    private javax.swing.JTable tableFunciones;
    private javax.swing.JTable tablePeliculas;
    // End of variables declaration//GEN-END:variables
}
