/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual;

import controlador.PeliculaBD;
import controlador.FuncionBD;
import javax.swing.JOptionPane;
import modelo.Pelicula;
import modelo.Funcion;

public class VtnRegistroPeli extends javax.swing.JFrame {

    Pelicula objPeli = null;
    Funcion objFuncion = null; 
    Principal objPrin = null;
    PeliculaBD pelBD =  new PeliculaBD();
    FuncionBD funBD = new FuncionBD();
    
    public VtnRegistroPeli() {
        initComponents();
    }

     public VtnRegistroPeli (Pelicula objPeli, Funcion objFuncion, Principal objPrin){
        
        this.objPeli = objPeli;
        this.objFuncion = objFuncion;
        this.objPrin = objPrin;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngIdioma = new javax.swing.ButtonGroup();
        lbTitulo = new javax.swing.JLabel();
        lbRegistrarPeli = new javax.swing.JLabel();
        lbCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lbNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lbDuracion = new javax.swing.JLabel();
        txtDuracion = new javax.swing.JTextField();
        lbClasificacion = new javax.swing.JLabel();
        comboxClasificacion = new javax.swing.JComboBox<>();
        lbGenero = new javax.swing.JLabel();
        comboxGenero = new javax.swing.JComboBox<>();
        lbIdioma = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        rdbEspañol = new javax.swing.JRadioButton();
        rdbIngles = new javax.swing.JRadioButton();
        rdbFrances = new javax.swing.JRadioButton();
        rdbPortugues = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtcodbus = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registros");

        lbTitulo.setBackground(new java.awt.Color(52, 71, 235));
        lbTitulo.setFont(new java.awt.Font("Waree", 1, 24)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(160, 46, 46));
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("CineTab");

        lbRegistrarPeli.setText("Registrar Pelicula");

        lbCodigo.setText("Codigo");

        lbNombre.setText("Nombre: ");

        lbDuracion.setText("Duracion:");

        lbClasificacion.setText("Clasificaion:");

        comboxClasificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "AA", "A", "B", "B15", "C", "D" }));
        comboxClasificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxClasificacionActionPerformed(evt);
            }
        });

        lbGenero.setText("Genero:");

        comboxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "Acción", "Ciencia Ficción", "Infantil", "Comedia", "Documental", "Drama", "Fantasia", "Musical", "Suspenso", "Terror" }));

        lbIdioma.setText("Idioma:");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btngIdioma.add(rdbEspañol);
        rdbEspañol.setText("Español");

        btngIdioma.add(rdbIngles);
        rdbIngles.setText("Ingles");

        btngIdioma.add(rdbFrances);
        rdbFrances.setText("Frances");
        rdbFrances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbFrancesActionPerformed(evt);
            }
        });

        btngIdioma.add(rdbPortugues);
        rdbPortugues.setText("Portugues");

        jLabel1.setText("Buscar Pelicula");

        txtcodbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodbusActionPerformed(evt);
            }
        });

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbRegistrarPeli)
                        .addGap(251, 251, 251))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRegresar)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbDuracion)
                            .addComponent(lbGenero)
                            .addComponent(lbCodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbIdioma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbFrances)
                    .addComponent(rdbPortugues)
                    .addComponent(rdbIngles)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDuracion)
                            .addComponent(txtCodigo)
                            .addComponent(comboxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNombre)
                                    .addComponent(lbClasificacion))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombre)
                                    .addComponent(comboxClasificacion, 0, 200, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnEliminar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnGuardar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtcodbus, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                        .addComponent(btnbuscar))))))
                    .addComponent(rdbEspañol))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbRegistrarPeli)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDuracion)
                    .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbClasificacion)
                    .addComponent(comboxClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGenero)
                    .addComponent(comboxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtcodbus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdioma)
                    .addComponent(rdbEspañol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbIngles)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEliminar)
                        .addComponent(btnGuardar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbFrances)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbPortugues)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        objPeli.setCodigo(txtCodigo.getText());
        objPeli.setNombre(txtNombre.getText());
        objPeli.setDuracion(txtDuracion.getText());
        objPeli.setClasificacion(comboxClasificacion.getSelectedItem().toString());
        objPeli.setGenero(comboxGenero.getSelectedItem().toString());
        objPeli.setIdioma(rdbEspañol.getText());
        objPeli.setIdioma(rdbFrances.getText());
        objPeli.setIdioma(rdbIngles.getText());
        objPeli.setIdioma(rdbPortugues.getText());
        
        pelBD.abrir();
        pelBD.insertarRegistro(objPeli);
        pelBD.cerrar();
        
        JOptionPane.showMessageDialog(this, "La pelicula se registró de forma correcta");

        limpiarCampos();
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void comboxClasificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxClasificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxClasificacionActionPerformed

    private void rdbFrancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbFrancesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbFrancesActionPerformed

    private void txtcodbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodbusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodbusActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        
        pelBD.abrir();
        objPeli = pelBD.consultarRegistro(txtCodigo.getText());
        
        if(objPeli != null){
            JOptionPane.showMessageDialog(this, "La pelicula existe");
            txtCodigo.setEditable(true);
            txtDuracion.setEditable(true);
            txtNombre.setEditable(true);
            comboxClasificacion.setEditable(true);
            comboxGenero.setEditable(true);
          
          
        }else{
            JOptionPane.showMessageDialog(this, "La pelicula no se encontró en la BD");
        }
        
        pelBD.cerrar();
        
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       
       pelBD.abrir();
        objPeli = pelBD.consultarRegistro(txtCodigo.getText());
        
        if(objPeli != null){
            
            pelBD.eliminarRegistro(objPeli);
        }else{
                JOptionPane.showMessageDialog(this, "La pelicula a eliminar no existe en la BD");

        }pelBD.cerrar(); 
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        
        limpiarCampos();
        objPrin.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarActionPerformed

     public void limpiarCampos(){
        
        txtCodigo.setText("");
        txtDuracion.setText("");
        txtNombre.setText("");
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnRegistroPeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnRegistroPeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnRegistroPeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnRegistroPeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnRegistroPeli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.ButtonGroup btngIdioma;
    private javax.swing.JComboBox<String> comboxClasificacion;
    private javax.swing.JComboBox<String> comboxGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbClasificacion;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbDuracion;
    private javax.swing.JLabel lbGenero;
    private javax.swing.JLabel lbIdioma;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbRegistrarPeli;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JRadioButton rdbEspañol;
    private javax.swing.JRadioButton rdbFrances;
    private javax.swing.JRadioButton rdbIngles;
    private javax.swing.JRadioButton rdbPortugues;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtcodbus;
    // End of variables declaration//GEN-END:variables
}
