/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual;

import controlador.PeliculaBD;
import controlador.FuncionBD;
import javax.swing.JOptionPane;
import modelo.Pelicula;
import modelo.Funcion;

public class VtnRegistro extends javax.swing.JFrame {

    Pelicula objPeli = null;
    Funcion objFuncion = null; 
    Principal objPrin = null;
    PeliculaBD pelBD =  new PeliculaBD();
    FuncionBD funBD = new FuncionBD();
    
    public VtnRegistro() {
        initComponents();
    }
    public VtnRegistro(Pelicula objPeli, Funcion objFuncion, Principal objPrin){
        
        this.objPeli = objPeli;
        this.objFuncion = objFuncion;
        this.objPrin = objPrin;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        tabPaneles = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lbNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        rdbEspañol = new javax.swing.JRadioButton();
        lbDuracion = new javax.swing.JLabel();
        rdbIngles = new javax.swing.JRadioButton();
        txtDuracion = new javax.swing.JTextField();
        rdbFrances = new javax.swing.JRadioButton();
        lbClasificacion = new javax.swing.JLabel();
        rdbPortugues = new javax.swing.JRadioButton();
        comboxClasificacion = new javax.swing.JComboBox<>();
        lbGenero = new javax.swing.JLabel();
        comboxGenero = new javax.swing.JComboBox<>();
        lbRegistrarPeli = new javax.swing.JLabel();
        lbIdioma = new javax.swing.JLabel();
        lbCodigo = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtcodbus = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbHora = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        lbDuracion1 = new javax.swing.JLabel();
        lbNumSala = new javax.swing.JLabel();
        comboxNumeroDeSala = new javax.swing.JComboBox<>();
        lbGenero1 = new javax.swing.JLabel();
        lbRegistrarFuncion = new javax.swing.JLabel();
        lbCodigoPeli = new javax.swing.JLabel();
        btnGuardar1 = new javax.swing.JButton();
        txtCodigoPeli = new javax.swing.JTextField();
        btnEliminar1 = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        cbtipo = new javax.swing.JComboBox<>();
        txtCapacidad = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTitulo.setBackground(new java.awt.Color(52, 71, 235));
        lbTitulo.setFont(new java.awt.Font("Waree", 1, 24)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(160, 46, 46));
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("CineTab");

        lbNombre.setText("Nombre: ");

        rdbEspañol.setText("Español");

        lbDuracion.setText("Duracion:");

        rdbIngles.setText("Ingles");

        rdbFrances.setText("Frances");

        lbClasificacion.setText("Clasificaion:");

        rdbPortugues.setText("Portugues");

        comboxClasificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "AA", "A", "B", "B15", "C", "D" }));

        lbGenero.setText("Genero:");

        comboxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "Acción", "Ciencia Ficción", "Infantil", "Comedia", "Documental", "Drama", "Fantasia", "Musical", "Suspenso", "Terror" }));

        lbRegistrarPeli.setText("Registrar Pelicula");

        lbIdioma.setText("Idioma:");

        lbCodigo.setText("Codigo");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel1.setText("Buscar Pelicula");

        txtcodbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodbusActionPerformed(evt);
            }
        });

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtcodbus, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnbuscar)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbRegistrarPeli)
                            .addGap(231, 231, 231))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbDuracion)
                                        .addComponent(lbGenero)
                                        .addComponent(lbCodigo))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbIdioma)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rdbPortugues)
                                .addComponent(rdbFrances)
                                .addComponent(rdbIngles)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(rdbEspañol)
                                    .addGap(220, 220, 220)
                                    .addComponent(btnEliminar)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnGuardar))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtDuracion)
                                        .addComponent(txtCodigo)
                                        .addComponent(comboxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(27, 27, 27)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbNombre)
                                        .addComponent(lbClasificacion))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNombre)
                                        .addComponent(comboxClasificacion, 0, 200, Short.MAX_VALUE))))))
                    .addGap(6, 6, 6)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtcodbus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar))
                .addContainerGap(186, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbRegistrarPeli)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbCodigo)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbNombre)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(29, 29, 29)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbDuracion)
                        .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbClasificacion)
                        .addComponent(comboxClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbGenero)
                        .addComponent(comboxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGuardar)
                        .addComponent(btnEliminar)
                        .addComponent(lbIdioma)
                        .addComponent(rdbEspañol))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(rdbIngles)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(rdbFrances)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(rdbPortugues)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        tabPaneles.addTab("Peliculas", jPanel1);

        lbHora.setText("Hora:");

        lbDuracion1.setText("Capacidad:");

        lbNumSala.setText("Numero de Sala");

        comboxNumeroDeSala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));

        lbGenero1.setText("Tipo de Sala");

        lbRegistrarFuncion.setText("Registrar Funcion");

        lbCodigoPeli.setText("Codigo Pelicula");

        btnGuardar1.setText("Guardar");
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });

        btnEliminar1.setText("Eliminar");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        cbtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "VIP", "3D", "IMAX" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(lbRegistrarFuncion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(181, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar1)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar1))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtCapacidad, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cbtipo, javax.swing.GroupLayout.Alignment.LEADING, 0, 171, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbDuracion1)
                        .addComponent(lbGenero1)
                        .addComponent(lbCodigoPeli))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtCodigoPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(27, 27, 27)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbHora)
                        .addComponent(lbNumSala))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtHora)
                        .addComponent(comboxNumeroDeSala, 0, 200, Short.MAX_VALUE))
                    .addGap(6, 6, 6)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbRegistrarFuncion)
                .addGap(71, 71, 71)
                .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(cbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar1)
                    .addComponent(btnEliminar1)
                    .addComponent(btnBuscar))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbCodigoPeli)
                        .addComponent(txtCodigoPeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbHora)
                        .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(29, 29, 29)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbDuracion1)
                        .addComponent(lbNumSala)
                        .addComponent(comboxNumeroDeSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(32, 32, 32)
                    .addComponent(lbGenero1)
                    .addContainerGap(143, Short.MAX_VALUE)))
        );

        tabPaneles.addTab("Funcion", jPanel2);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabPaneles)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPaneles, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcodbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodbusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodbusActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed

        pelBD.abrir();
        objPeli = pelBD.consultarRegistro(txtCodigo.getText());

        if(objPeli != null){
            JOptionPane.showMessageDialog(this, "La pelicula existe");
            txtCodigo.setEditable(true);
            txtDuracion.setEditable(true);
            txtNombre.setEditable(true);
            comboxClasificacion.setEditable(true);
            comboxGenero.setEditable(true);

        }else{
            JOptionPane.showMessageDialog(this, "La pelicula no se encontró en la BD");
        }

        pelBD.cerrar();

    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       
        objPeli.setCodigo(txtCodigo.getText());
        objPeli.setNombre(txtNombre.getText());
        objPeli.setDuracion(txtDuracion.getText());
        objPeli.setClasificacion(comboxClasificacion.getSelectedItem().toString());
        objPeli.setGenero(comboxGenero.getSelectedItem().toString());
        objPeli.setIdioma(rdbEspañol.getText());
        objPeli.setIdioma(rdbFrances.getText());
        objPeli.setIdioma(rdbIngles.getText());
        objPeli.setIdioma(rdbPortugues.getText());
        
        pelBD.abrir();
        pelBD.insertarRegistro(objPeli);
        pelBD.cerrar();
        
        JOptionPane.showMessageDialog(this, "La pelicula se registró de forma correcta");

        limpiarCampos();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
         pelBD.abrir();
        objPeli = pelBD.consultarRegistro(txtCodigo.getText());
        
        if(objPeli != null){
            
            pelBD.eliminarRegistro(objPeli);
        }else{
                JOptionPane.showMessageDialog(this, "La pelicula a eliminar no existe en la BD");

        }pelBD.cerrar(); 
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        
        limpiarCampos();
        objPrin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        
        objFuncion.setCodigoPelicula(txtCodigoPeli.getText());
        objFuncion.setHora(Integer.parseInt(txtHora.getText()));
        objFuncion.setCapacidad(Integer.parseInt(txtCapacidad.getText()));
        objFuncion.setNumeroDeSala(Integer.parseInt(comboxNumeroDeSala.getSelectedItem().toString()));
        objFuncion.setTipoDeSala(cbtipo.getSelectedItem().toString());       
        
    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       
         funBD.abrir();
        objFuncion = funBD.consultarRegistro(txtCodigoPeli.getText());
        
        if(objFuncion != null){
            JOptionPane.showMessageDialog(this, "La funcion existe");
            txtCodigoPeli.setEditable(true);
            txtHora.setEditable(true);
            txtCapacidad.setEditable(true);
            comboxNumeroDeSala.setEditable(true);
            cbtipo.setEditable(true);

        }else{
             JOptionPane.showMessageDialog(this, "La funcion no existe");

        }funBD.cerrar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        
        funBD.abrir();
        objFuncion = funBD.consultarRegistro(txtCodigoPeli.getText());
        
        if(objFuncion != null){
            
            funBD.eliminarRegistro(objFuncion);
        }else{
                JOptionPane.showMessageDialog(this, "La funcion a eliminar no existe en la BD");

        }funBD.cerrar();
        
    }//GEN-LAST:event_btnEliminar1ActionPerformed

       public void limpiarCampos(){
        
        txtCodigo.setText("");
        txtDuracion.setText("");
        txtNombre.setText("");
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JComboBox<String> cbtipo;
    private javax.swing.JComboBox<String> comboxClasificacion;
    private javax.swing.JComboBox<String> comboxGenero;
    private javax.swing.JComboBox<String> comboxNumeroDeSala;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbClasificacion;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbCodigoPeli;
    private javax.swing.JLabel lbDuracion;
    private javax.swing.JLabel lbDuracion1;
    private javax.swing.JLabel lbGenero;
    private javax.swing.JLabel lbGenero1;
    private javax.swing.JLabel lbHora;
    private javax.swing.JLabel lbIdioma;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbNumSala;
    private javax.swing.JLabel lbRegistrarFuncion;
    private javax.swing.JLabel lbRegistrarPeli;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JRadioButton rdbEspañol;
    private javax.swing.JRadioButton rdbFrances;
    private javax.swing.JRadioButton rdbIngles;
    private javax.swing.JRadioButton rdbPortugues;
    private javax.swing.JTabbedPane tabPaneles;
    private javax.swing.JTextField txtCapacidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigoPeli;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtcodbus;
    // End of variables declaration//GEN-END:variables
}
